baseURL = 'https://hip-nl.github.io/'
languageCode = 'en-us'
title = 'Historical Income Panel for the Netherlands'

theme = "gokarna"

[params]
    description = "A unique large-scale historical income panel for the Netherlands, 1850â€“1922"
    avatarURL = "/images/hipnl-logo-round.png"
    avatarSize = "size-m"

[menu]
    [[menu.main]]
        identifier = "project"
        name = "project"
        url = "/project"
        weight = 1
    
    [[menu.main]]
        identifier = "team"
        name = "team"
        url = "/team"
        weight = 2
    [[menu.main]]
        identifier = "sample"
        name = "sample"
        url = "/sample"
        weight = 2
    [[menu.main]]
        identifier = "data"
        name = "data"
        url = "/data"
        weight = 2
    [[menu.main]]
        identifier = "papers"
        name = "papers"
        url = "/papers/"
        weight = 3
    [[menu.main]]
        identifier = "news"
        name = "news"
        url = "/news/"
        weight = 3
    [[menu.main]]
        identifier = "github"
        pre = "<span data-feather='github'></span>"
        url = "https://github.com/HIP-NL"
        weight = 4